baseurl = "https://learn.rsquaredacademy.com/"
languageCode = "en-us"
title = "Rsquared Academy - Learn Data Science"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-57270671-32"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "https://tutorials.rsquaredacademy.com/"
    weight = 1
[[menu.main]]
    name = "Explore Online Courses"
    url = "https://rsquared-academy.thinkific.com"   
    weight = 2
[[menu.main]]
    name = "Free Tutorials"
    url = "https://tutorials.rsquaredacademy.com/"
    weight = 3

[params]
    description = "Rsquared Academy - Learn Data Science"
    keywords = "data, science, r, python, data visualization, data wrangling, machine learning, data science, statistics"
    twitterAuthor = "@rsquaredacademy"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.jpeg"
    width = 50
    height = 50
    alt = "Rsquared Academy"

    [params.icon]
    url = "favicon.ico"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"